# Vercel Build Configuration
# This file helps optimize the Vercel build process

# PHP Version
php: 8.1

# Build Command (runs during deployment)
build:
  commands:
    - composer install --no-dev --optimize-autoloader
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache

# Environment Variables Required
environment:
  - APP_NAME
  - APP_ENV
  - APP_KEY
  - APP_DEBUG
  - APP_URL
  - DB_CONNECTION
  - DB_HOST
  - DB_PORT
  - DB_DATABASE
  - DB_USERNAME
  - DB_PASSWORD

# Health Check Endpoint
health_check: /health